### ISSUE TITLE
Settings window cuts off buttons

### ISSUE THREAD

**Issue by aricooperdavis** [gazugafan/RestStop#1]
Brilliant app, thank you! 

One slight issue that I've experienced is that the settings window cuts off the buttons at the bottom making them impossible to read.

Still usable, but it would be nice if we could resize that window to fix the problem, or if the window scaled to encompass the buttons?

<img width="497" alt="bug" src="https://user-images.githubusercontent.com/8947634/54622046-b970bd00-4a60-11e9-8146-370fb786f4df.png">

**Comment by gazugafan** [comment]
Glad you like it, and thanks for the bug report! Weird that the buttons are cutoff. I'm not seeing the problem on my end, but I'll dig into it soon and try to get to the bottom of it.

In the meantime, those buttons are, from left to right: "Reset to Defaults", "Cancel", and "Save Changes". And there's nothing else in the screenshot that's cutoff or missing.

**Comment by aricooperdavis** [comment]
Thank you, if you need any details of monitor size, magnification etc then please let me know!

**Comment by gazugafan** [comment]
Yeah, any more info could potentially help! If I had to guess, I'd think maybe the window has a DPI scaling issue.

**Comment by aricooperdavis** [comment]
I've just noticed that the problem only seems to occur if I start the app when using my laptop as a laptop, and then plug my laptop into an external display. As such I suspect it's probably a generic windows problem rather than anything on your end, so I'm happy to close the issue 👍

**Comment by gazugafan** [comment]
Cool! Well I'll close this for now, then. Let me know if it gives you more trouble and I'll dig into it.
