### ISSUE TITLE
Hard to see the hourglass icon in system tray

### ISSUE THREAD

**Issue by thedc6324** [gazugafan/RestStop#6]
In Windows 11 Light UI, it is hard to see the hourglass icon due to color problem. Both the icon and background have the same color. Please fix that.
![image_2023-12-16_201703270](https://github.com/gazugafan/RestStop/assets/41643740/2a9c345f-3d83-4570-b2d1-9910c3876a78)

**Comment by gazugafan** [comment]
Makes sense! I don't use this anymore, though, and have no motivation to work on it. You can rebuild it yourself with modified icons, or maybe even use a resource editing app to hack in new icons?

PRs welcome if you want to take the time to get the icons to respect the user's theme :)

I did something similar here if you want to take a stab at it...
https://github.com/gazugafan/fingerpass/blob/35e162746cb83c4a39114ea44f6804f3c4322b1a/fingerpass/TrayIcon.cs#L58

**Comment by WildGenius** [comment]
Out of curiosity, why don't you use this anymore? RestStop is certainly the best app of its type I've found!

**Comment by gazugafan** [comment]
Glad you like it @WildGenius ! I got pretty good at self-regulating my computer use after awhile, so I just don't use this sort of app anymore.
